name: recsys2
channels:
  - gurobi
  - conda-forge
  - defaults
dependencies:
  - pip
  - python==3.7
  - pip:
    - gurobipy==9.1.2
    - tensorflow==1.15.2
    - numpy
    - torch
    - tqdm
    - pandas
    - mip
    - cornac==1.14.2
    - ipykernel==6.16.2
    - protobuf==3.20.0
    - pyyaml
    - ipywidgets
    - seaborn